[build-system]
requires = ["ChimeraX-BundleBuilder>=1.0"]
build-backend = "chimerax.bundle_builder.cx_pep517"

[project]
name = "ChimeraX-VolgridUsage"
version = "1.0"
authors = [
    {name = "Volgrid Usage Plugin", email = "contact@example.com"},
]
description = "Volumetric grid analysis tool for ChimeraX with Smiffer and APBS integration"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.8"
dynamic = ["classifiers", "dependencies"]
keywords = ["ChimeraX", "plugin", "volgrid", "smiffer", "apbs", "visualization"]
urls = {Homepage = "https://github.com/example/chimerax-volgrid-usage"}

[project.optional-dependencies]
dev = ["ChimeraX-BundleBuilder>=1.0"]

[chimerax]
pure = true
min-session-ver = 1
max-session-ver = 1
custom-init = false
categories = ["General"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research", 
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Visualization"
]

[chimerax.tool."VolgridUsage"]
category = "General"
description = "Volumetric grid analysis with Smiffer and APBS integration"
